[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Ryan Barth <ryan@barth.tech>"]

[dependencies]
diesel = { version = "*", features = ["postgres"] }
diesel_codegen = { version = "*", features = ["postgres"] }
dotenv = "*"
